name: Mypy

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy
    - name: Install
      run: python setup.py install
    - name: Analysing the code with mypy
      run: mypy -m evilemu
